name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Manually install GHC and Cabal
        run: |
          echo "Installing Haskell tools..."
          curl -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 sh
          ~/.ghcup/bin/ghcup install ghc 9.2.7
          ~/.ghcup/bin/ghcup set ghc 9.2.7
          ~/.ghcup/bin/ghcup install cabal 3.10.1.0
          ~/.ghcup/bin/ghcup set cabal 3.10.1.0
          echo "$HOME/.cabal/bin" >> $GITHUB_PATH
          echo "$HOME/.ghcup/bin" >> $GITHUB_PATH

      - name: Cache cabal packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-cabal-cleanfix-${{ hashFiles('**/*.cabal', 'cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-cabal-cleanfix-

      - name: Build and run site
        run: |
          cabal build site
          $(cabal list-bin site) build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
          branch: gh-pages
          clean: true
